{{- if .Values.certificateManager.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "aidp-gateway.certManagerName" . }}
  namespace: {{ .Values.certificateManager.secretNamespace }}
  labels:
    {{- include "aidp-gateway.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "patch"]
- apiGroups: ["gateway.networking.k8s.io"]
  resources: ["gateways"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "aidp-gateway.certManagerName" . }}
  namespace: {{ .Values.certificateManager.secretNamespace }}
  labels:
    {{- include "aidp-gateway.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "aidp-gateway.certManagerName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "aidp-gateway.certManagerName" . }}
{{- end }}
