{{- if .Values.gatewayManager.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aidp-gateway.gatewayManagerName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aidp-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway-manager
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "aidp-gateway.gatewayManagerName" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - name: http
    port: {{ .Values.gatewayManager.service.port }}
    targetPort: http
{{- end }}
