{{- if .Values.gatewayManager.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aidp-gateway.gatewayManagerName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aidp-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway-manager
{{- end }}
