---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: mock-memory-extauthz
  namespace: envoy-gateway-system
  labels:
    {{- include "aidp-mock-memory.labels" . | nindent 4 }}
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: mock-memory-route
  extAuth:
    grpc:
      backendRefs:
      - name: pep-proxy
        namespace: opa
        port: 9000
    failOpen: false
    bodyToExtAuth:
      maxRequestBytes: 8192
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyExtensionPolicy
metadata:
  name: mock-memory-extproc
  namespace: envoy-gateway-system
  labels:
    {{- include "aidp-mock-memory.labels" . | nindent 4 }}
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: mock-memory-route
  extProc:
  - backendRefs:
    - name: resource-sync
      namespace: resource-sync
      port: 8082
    processingMode:
      request:
        body: Streamed
      response:
        body: Streamed
    failOpen: true
