apiVersion: v1
kind: Service
metadata:
  name: opal-server
  namespace: opa
  labels:
    app: opal-server
    {{- include "opa.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.opalServer.port }}
    targetPort: {{ .Values.opalServer.port }}
    name: http
  selector:
    app: opal-server
