apiVersion: v1
kind: Service
metadata:
  name: iam-store
  namespace: keycloak
  labels:
    app: iam-store
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.postgres.port }}
    targetPort: {{ .Values.postgres.port }}
    name: postgres
  selector:
    app: iam-store
