apiVersion: v1
kind: ConfigMap
metadata:
  name: db-provisioner-config
  namespace: {{ .Values.superSecret.namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  databases.yaml: |
    databases:
    {{- range .Values.databases }}
      - name: {{ .name }}
        user: {{ .user }}
        secretName: {{ .secretName }}
        secretNamespace: {{ .secretNamespace }}
    {{- end }}
