apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opengauss
  namespace: {{ .Values.superSecret.namespace }}
spec:
  serviceName: opengauss
  replicas: 1
  selector:
    matchLabels:
      app: opengauss
  template:
    metadata:
      labels:
        app: opengauss
    spec:
      containers:
        - name: opengauss
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: GS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.superSecret.name }}
                  key: username
            - name: GS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.superSecret.name }}
                  key: password
            - name: GS_PORT
              value: "5432"
            - name: GS_NODENAME
              value: gaussdb
          ports:
            - containerPort: 5432
              name: gs
          volumeMounts:
            - name: data
              mountPath: /var/lib/opengauss
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 20
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 60
            periodSeconds: 15
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: {{ .Values.storage.size }}
