apiVersion: v1
kind: Service
metadata:
  name: opengauss
  namespace: {{ .Values.superSecret.namespace }}
spec:
  selector:
    app: opengauss
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5432
      name: gs
