apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ .Values.gateway.className }}
  labels:
    {{- include "aidp-gateway.labels" . | nindent 4 }}
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: {{ .Values.gateway.name }}-config
    namespace: {{ include "aidp-gateway.gatewayNamespace" . }}
