apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-kb
  namespace: {{ .Values.namespace }}
  labels:
    app: mock-kb
    {{- include "aidp-mock-kb.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: mock-kb
  template:
    metadata:
      labels:
        app: mock-kb
    spec:
      containers:
      - name: mock-kb
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        ports:
        - containerPort: {{ .Values.port }}
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.port }}
          initialDelaySeconds: 3
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.port }}
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: mock-kb
  namespace: {{ .Values.namespace }}
  labels:
    app: mock-kb
    {{- include "aidp-mock-kb.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
    name: http
  selector:
    app: mock-kb
